import type { RequestPreset } from './lab-testing-types';

export const requestPresets: RequestPreset[] = [
  {
    id: 'migration-monolith-catalog',
    moduleId: 'migration',
    label: 'Monolith catalog baseline',
    description: 'Capture baseline catalog behavior before shifting a route.',
    concepts: ['Strangler Fig', 'Parallel Run'],
    targetName: 'monolith',
    method: 'GET',
    path: '/api/catalog',
    headers: { 'X-Lab-Scenario': 'baseline' },
    expectedObservation: 'The monolith returns catalog items before any route is redirected.',
    safety: 'read_only',
  },
  {
    id: 'migration-catalog-service',
    moduleId: 'migration',
    label: 'Extracted catalog read',
    description: 'Read directly from the extracted catalog service after route shifting.',
    concepts: ['Strangler Fig'],
    targetName: 'catalog-service',
    method: 'GET',
    path: '/api/catalog',
    headers: { 'X-Lab-Scenario': 'shifted' },
    expectedObservation: 'The extracted service responds with equivalent catalog data.',
    safety: 'read_only',
  },
  {
    id: 'consistency-kv-read',
    moduleId: 'consistency',
    label: 'Read demo key',
    description: 'Read a known key before and after changing partition state.',
    concepts: ['CAP', 'Replication'],
    targetName: 'kv-store',
    method: 'GET',
    path: '/api/kv/demo-key',
    expectedObservation: 'The value and partition marker show how the store behaves.',
    safety: 'read_only',
  },
  {
    id: 'resiliency-order-list',
    moduleId: 'resiliency',
    label: 'Order list under fault',
    description: 'List orders before, during, and after a fault injection drill.',
    concepts: ['Bulkhead', 'Timeouts'],
    targetName: 'order-service',
    method: 'GET',
    path: '/api/orders',
    expectedObservation: 'Latency and failures should change when faults are active.',
    safety: 'read_only',
  },
  {
    id: 'workflows-create-order',
    moduleId: 'workflow',
    label: 'Create saga order',
    description: 'Create a small order to observe downstream workflow behavior.',
    concepts: ['Saga', 'Messaging'],
    targetName: 'order-service',
    method: 'POST',
    path: '/api/orders',
    headers: { 'Content-Type': 'application/json' },
    body: '{"items":["album-1"],"totalAmount":19.99}',
    expectedObservation: 'The order is created and an order event becomes observable.',
    safety: 'state_changing',
  },
  {
    id: 'observability-payment-stats',
    moduleId: 'observability',
    label: 'Payment stats trace',
    description: 'Fetch payment stats while watching traces and logs.',
    concepts: ['Tracing', 'Metrics'],
    targetName: 'payment-service',
    method: 'GET',
    path: '/api/payments/stats',
    expectedObservation: 'The response should correlate with service metrics and traces.',
    safety: 'read_only',
  },
];

export function presetsForModule(moduleId: string) {
  return requestPresets.filter((preset) => preset.moduleId === moduleId);
}
